Feature EPL-1727: First model of the Breadcrums component
etendosoftware/com.etendorx.workspace-ui pull request #100
Opened 2024-08-06 18:28 UTC by Sankku

2024-08-07 11:55 UTC, tomyrodeghiero approved these changes

2024-08-07 12:37 UTC, sjcuello approved these changes

2024-08-07 16:06 UTC, LuuchoRocha requested changes
Excellent job!
The only missing thing is to address the callbacks issues

2024-08-07 16:06 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Breadcrums/index.tsx
> +        MenuListProps={{ sx: menuStyle }}>
move out this into a constant

2024-08-07 16:06 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Breadcrums/index.tsx
> +                  onToggle={() => handleToggle(action.id)}
note to future ourselves: we need to develop some helper to create this handlers inside map loops and avoid the usage of arrow functions

2024-08-08 11:55 UTC, tomyrodeghiero submitted a review, later dismissed
I agree with @LuuchoRocha's comments

2024-08-08 18:38 UTC, merged