Feature ETP-81: Dynamic Menu Generation Based on Metadata
etendosoftware/com.etendorx.workspace-ui pull request #123
Opened 2024-08-29 16:15 UTC by LuuchoRocha

## Fixed existing menu after refactoring metadata servlet

2024-08-29 18:23 UTC, leandroallemandismf approved these changes

2024-08-29 18:23 UTC, leandroallemandismf commented on packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
> +    if (item.type === MenuType.Summary) {
is it checked if “item” is undefined it does not break the component?

2024-08-30 12:33 UTC, Sankku requested changes

2024-08-30 12:33 UTC, Sankku commented on packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
> +      {item.children ? (
I think is better to use && instead. Or if u want to use '?'  add an else return null

2024-08-30 16:20 UTC, tomirodeghiero approved these changes

2024-08-30 16:20 UTC, tomirodeghiero commented on packages/ComponentLibrary/src/components/Drawer/index.tsx
> +            <DrawerSection key={item.id} item={item} onClick={onClick} />
Good change :)
Very important to prevent future warnings

2024-09-10 13:41 UTC, merged