Feature EM-337: Button group of refresh and New line
etendosoftware/com.etendorx.workspace-ui pull request #127
Opened 2024-09-11 11:49 UTC by Sankku

Button group of refresh and New line that change depending of the view

Table View
![image](https://github.com/user-attachments/assets/488caa0d-b3bc-443c-8a4f-25e4bfcebabf)

Form View
![image](https://github.com/user-attachments/assets/9fe85346-4e93-43a6-8637-924ade05ce8c)

2024-09-11 14:18 UTC, LuuchoRocha requested changes

2024-09-11 14:18 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Table/ExpandMenu/index.tsx
> +const ExpandMenu: React.FC<ExpandMenuProps> = ({ anchorEl, onClose, open }) => {
```suggestion
const ExpandMenu = ({ anchorEl, onClose, open }: ExpandMenuProps) => {
```

2024-09-11 14:18 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Table/ExpandMenu/index.tsx
> +
```suggestion
const bottomRightOrigin = {
  vertical: 'bottom',
  horizontal: 'right',
}
```

2024-09-11 14:18 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Table/ExpandMenu/index.tsx
> +          placeholder="Enter value"
Please use the internationalization method `t('...')`

2024-09-12 11:53 UTC, tomirodeghiero requested changes

2024-09-12 11:53 UTC, tomirodeghiero commented on packages/MainUI/src/index.css
> -  background: linear-gradient(180deg, #C6D3FF 30%, #F5F6FA 100%);
Move colors as contants

2024-09-12 11:53 UTC, tomirodeghiero commented on packages/storybook/src/stories/Components/Table/toolbarFormviewMock.tsx
Set the width and height to 16 as constant

2024-09-12 11:53 UTC, tomirodeghiero commented on packages/storybook/src/stories/Components/Table/toolbarMock.tsx
Set the width and height to 16 as constant

2024-09-12 11:57 UTC, tomirodeghiero approved these changes

2024-09-12 12:57 UTC, leandroallemandismf approved these changes

2024-09-12 20:17 UTC, LuuchoRocha approved these changes

2024-09-12 20:17 UTC, merged