Feature ETP-273: Talbe Dir Selector
etendosoftware/com.etendorx.workspace-ui pull request #137
Opened 2024-09-25 13:22 UTC by Sankku

![image](https://github.com/user-attachments/assets/634da029-c873-48af-8b95-ffc47bd94fc8)
![image](https://github.com/user-attachments/assets/3209b3e8-0be2-45e7-84b3-e1cc2bcf7db1)

2024-09-25 16:06 UTC, LuuchoRocha commented on packages/MainUI/src/components/DynamicTable/index.tsx
> +  );
thanks!

2024-09-25 16:08 UTC, LuuchoRocha requested changes

2024-09-25 16:08 UTC, LuuchoRocha commented on packages/MainUI/src/components/FormView/FormField.tsx
> +            <TableDirSelector name={name} onChange={onChange} field={field} />
Am I wrong or this is NOT the latest version we wrote?

2024-09-26 16:27 UTC, LuuchoRocha approved these changes

2024-09-26 17:03 UTC, closed without merging

2024-09-26 17:52 UTC, Sankku commented
asdasd