Feature ETP-753: Implement execution of action buttons
etendosoftware/com.etendorx.workspace-ui pull request #215
Opened 2024-11-26 12:47 UTC by Sankku

The execution of actions via action buttons involves several components working together to provide a seamless user experience. 
![image](https://github.com/user-attachments/assets/c423d985-4f6f-47ea-80d1-c63f41e8caeb)

2024-11-27 15:13 UTC, LuuchoRocha commented on packages/MainUI/components/Table/index.tsx
> +        setSelectedRecord(row.original as never);
I think we could rely in the metadata context and the selected records there, but I will check

2024-12-02 12:48 UTC, LuuchoRocha requested changes

2024-12-02 12:48 UTC, LuuchoRocha commented on packages/MainUI/components/Toolbar/GenericProcessButton.tsx
> +};
```suggestion

const disabledStyle = {
  opacity: 0.5,
  cursor: 'not-allowed',
};

const enabledStyle = {
  opacity: 1,
  cursor: 'pointer',
}

const GenericProcessButton: React.FC<ProcessButtonProps> = ({ button, onClick, disabled }) => {
  return (
    <IconButton
      onClick={onClick}
      disabled={disabled}
      title={button.name}
      data-testid={`process-button-${button.id}`}
      style={disabled ? disabledStyle : enabledStyle}
    />
  );
};
```

2024-12-02 12:48 UTC, LuuchoRocha commented on packages/MainUI/components/Toolbar/Toolbar.tsx
> +  };
wrap this with useCallback

2024-12-02 12:48 UTC, LuuchoRocha commented on packages/MainUI/components/Toolbar/Toolbar.tsx
> +  };
is there any way you could simplify, refactor into smaller pieces and re-usable ones?

2024-12-02 12:48 UTC, LuuchoRocha commented on packages/MainUI/hooks/useProcessExecution.ts
> +  const executeProcess = async ({ button, recordId, params = {} }: ExecuteProcessParams): Promise<ProcessResponse> => {
wrap this with useCallback

2024-12-03 12:50 UTC, NazaTarrili-Futit approved these changes

2024-12-03 15:28 UTC, LuuchoRocha approved these changes

2024-12-03 15:28 UTC, merged