Feature ETP-871: Structure for report page
etendosoftware/com.etendorx.workspace-ui pull request #225
Opened 2024-12-11 18:33 UTC by Sankku

2024-12-12 15:54 UTC, LuuchoRocha commented
@Sankku please address the build issues

2024-12-13 16:29 UTC, LuuchoRocha requested changes

2024-12-13 16:29 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/hooks/useItemType.ts
> +  }, []);
please move this outside of the hook (it doesn't need to be defined as a callback inside of the hook, it's a regular helper)

2024-12-13 16:29 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/hooks/useItemType.ts
> +  return { handleItemClick };
```suggestion
  return handleItemClick;
```

2024-12-13 16:29 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Drawer/DrawerSection/index.tsx
> +  const { handleItemClick } = useItemActions({
```suggestion
  const handleItemClick = useItemActions({
```

2024-12-18 11:52 UTC, LuuchoRocha approved these changes

2024-12-18 19:12 UTC, leandroallemandismf approved these changes

2024-12-18 19:14 UTC, leandroallemandismf approved these changes

2024-12-18 22:49 UTC, LuuchoRocha submitted a review, later dismissed
.

2024-12-18 23:05 UTC, tomirodeghiero approved these changes

2024-12-20 10:15 UTC, LuuchoRocha requested changes
Great job!

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Drawer/index.tsx
> +        onProcessClick(processId);
Is it possible to remove this callback and use onProcessClick directly, without wrapping it?

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/Drawer/index.tsx
> +        onReportClick(reportId);
Is it possible to remove this callback and use onReportClick directly, without wrapping it?

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/FormView/selectors/DateSelector.tsx
> +        InputProps={{
`name` prop is missing here

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/ComponentLibrary/src/components/FormView/selectors/DateSelector.tsx
> +        InputLabelProps={{ shrink: true }}
Create a constant (out of the component) for InputLabelProps

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/EtendoHookBinder/src/hooks/useReportMetadata.ts
> +  }, [reportId, fetchMetadata]);
Maybe reportId is not needed here

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/MainUI/app/report/[reportId]/page.tsx
> +  };
Move this to line 15 before the first `if` and wrap it with useCallback

2024-12-20 10:15 UTC, LuuchoRocha commented on packages/MainUI/tsconfig.json
Revert this changes

2024-12-20 12:31 UTC, Sankku commented on packages/ComponentLibrary/src/components/FormView/selectors/DateSelector.tsx
> +        InputProps={{
But is not?

2024-12-20 13:32 UTC, closed without merging