Feature EPL-1561: NotificationButton first version
etendosoftware/com.etendorx.workspace-ui pull request #42
Opened 2024-06-13 14:28 UTC by Sankku

2024-06-13 15:31 UTC, sjcuello requested changes
Don't forget to complete your merges and PLEASE check all files before mark ready to validate

2024-06-13 19:49 UTC, leandroallemandismf approved these changes

2024-06-13 19:49 UTC, leandroallemandismf commented on packages/ComponentLibrary/src/components/NotificationsButton/index.tsx
> +  const notificationCount = NOTIFICATIONS.length;
Shouldn't you take this value from the prop and not insert it statically from the component?

2024-06-14 11:22 UTC, sjcuello commented on packages/ComponentLibrary/src/components/NotificationsButton/index.tsx
> +            badgeContent={notificationCount > 99 ? '99+' : notificationCount}
agree

2024-06-14 13:00 UTC, sjcuello approved these changes

2024-06-14 13:34 UTC, merged