Feature EPL-1561: Improved usability of the component
etendosoftware/com.etendorx.workspace-ui pull request #44
Opened 2024-06-18 00:31 UTC by Sankku

2024-06-18 16:34 UTC, leandroallemandismf requested changes

2024-06-18 19:57 UTC, Sankku commented on packages/ComponentLibrary/src/components/NotificationsButton/index.tsx
> +          {...iconButtonProps}
I dont understand the purpose of this commentary, as I understand it we dont need to do that, maybe we can do a short meet to clarify it

2024-06-24 12:05 UTC, sjcuello approved these changes

2024-06-24 12:14 UTC, leandroallemandismf approved these changes

2024-06-24 13:17 UTC, tomyrodeghiero approved these changes

2024-06-24 13:42 UTC, merged