Feature EPL-1562: Add Notification Modal
etendosoftware/com.etendorx.workspace-ui pull request #45
Opened 2024-06-18 00:38 UTC by Sankku

2024-06-18 14:48 UTC, tomyrodeghiero requested changes

2024-06-18 14:48 UTC, tomyrodeghiero commented on packages/ComponentLibrary/src/components/NotificationsModal/styles.ts
> +const NEUTRAL_10 = '#F5F6FA';
These styles are already defined in colors.ts file, it would be better to use them from there or add them there and use them here

2024-06-18 14:48 UTC, tomyrodeghiero commented on packages/ComponentLibrary/src/components/NotificationsModal/styles.ts
> +  rigthContainer: { alignItems: 'center', display: 'flex' },
Check fromatter here

2024-06-18 14:48 UTC, tomyrodeghiero commented on packages/MainUI/src/screens/Home/index.tsx
> +            <NotificationModal
Is it correct to write this in Spanish? Move to constants file

2024-06-18 16:34 UTC, leandroallemandismf requested changes

2024-06-18 18:05 UTC, Sankku commented on packages/MainUI/src/screens/Home/index.tsx
> +              emptyStateImage={image}
Maybe I can make the image for default and if there isn't an image you can pass one by params, because it makes the component more reusable

2024-06-18 18:11 UTC, Sankku commented on packages/MainUI/src/screens/Home/index.tsx
> +        <NotificationBase
What you mean by this, the actual name of "NotificationBase" or you propose another composition for the component?

2024-06-19 16:48 UTC, sjcuello commented on packages/MainUI/src/screens/Home/index.tsx
> +              emptyStateImage={image}
The empty state never is a param

2024-06-19 16:51 UTC, sjcuello commented on packages/ComponentLibrary/src/components/NotificationsModal/types.ts
> +  emptyStateImage: string;
The  empty state is just that, a special case. 
By now, we don't have to customize an empty case.

2024-06-19 16:51 UTC, sjcuello approved these changes

2024-06-24 12:07 UTC, sjcuello commented on packages/ComponentLibrary/src/components/NotificationsModal/index.tsx
> +  const handleClose = () => {
Delete this function. 
Always code in a generic way

2024-06-24 12:08 UTC, sjcuello commented on packages/ComponentLibrary/src/components/NotificationsModal/index.tsx
> +import { NOTIFICATIONS } from '../NotificationItem/mock';
The mock have to be used just when the component is called.
Change the logic

2024-06-24 17:31 UTC, leandroallemandismf approved these changes

2024-06-24 18:45 UTC, merged