Feature EPL-1493: First model of the new Navbar
etendosoftware/com.etendorx.workspace-ui pull request #82
Opened 2024-07-02 18:25 UTC by Sankku

2024-07-03 14:00 UTC, tomyrodeghiero requested changes

2024-07-03 14:00 UTC, tomyrodeghiero commented on packages/ComponentLibrary/src/components/Nav/Nav.styles.ts
> +    width: '91rem',
Is this width of **'91rem'** correct?

2024-07-03 14:00 UTC, tomyrodeghiero commented on packages/ComponentLibrary/src/components/Nav/Nav.styles.ts
> +    width: '14rem',
Is this constant width correct?

2024-07-03 14:00 UTC, tomyrodeghiero commented on packages/ComponentLibrary/src/components/Nav/Nav.styles.ts
> +  boxStyles: {},
The **boxStyles** is empty 🧐

2024-07-03 14:00 UTC, tomyrodeghiero commented on packages/ComponentLibrary/src/components/Nav/Nav.tsx
> +interface NavProps {
Move **interface** to its corresponding file

2024-07-05 12:53 UTC, tomyrodeghiero approved these changes

2024-07-10 12:26 UTC, sjcuello commented on packages/ComponentLibrary/src/components/ProfileModal/UserProfile.tsx
>  import { user } from './UserMock';
This component is using mocks

2024-07-10 13:29 UTC, sjcuello approved these changes

2024-07-10 13:38 UTC, merged