Feature EPL-1567 EPL-1568 EPL-1569: SearchModal Component
etendosoftware/com.etendorx.workspace-ui pull request #83
Opened 2024-07-05 17:14 UTC by tomyrodeghiero

2024-07-08 11:47 UTC, sjcuello approved these changes

2024-07-09 13:18 UTC, Sankku requested changes

2024-07-09 13:18 UTC, Sankku commented on packages/ComponentLibrary/src/components/SecondaryTabs/styles.ts
> +    height: '36px',
swap px to rem

2024-07-09 13:18 UTC, Sankku commented on packages/ComponentLibrary/src/components/SecondaryTabs/styles.ts
> +    height: '28px',
idem

2024-07-09 13:27 UTC, merged