Feature EPL-1597: [Storybook] Update select in profile
etendosoftware/com.etendorx.workspace-ui pull request #90
Opened 2024-07-11 18:46 UTC by Sankku

2024-07-11 19:28 UTC, sjcuello requested changes
Pay attention to your prettier configuration.
IDK why are there a lot of indentation changes

2024-07-11 19:28 UTC, sjcuello commented on packages/ComponentLibrary/src/components/Input/Select/index.tsx
> +import { ISelectInput, Option } from './types'; // Asegúrate de que Option está tipado
Do not use comment if it's not necessary.
Never use Spanish to comment

2024-07-16 11:36 UTC, tomyrodeghiero approved these changes

2024-07-17 22:56 UTC, sjcuello approved these changes

2024-07-19 17:45 UTC, merged